version: '3.1'

services:
  bd_mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
       - MYSQL_ROOT_PASSWORD
       - MYSQL_DATABASE
       - MYSQL_USER
       - MYSQL_PASSWORD
    volumes:
       - ./volumenes/mysql:/var/lib/mysql
       - ./volumenes/mysql-init-files:/docker-entrypoint-initdb.d
       - ./my.cnf:/etc/mysql/my.cnf
    ports:
       - 3306:3306
    expose:
       - 3306
    networks:
       - default

  app_php:
    build: .
    image: webdevops/php-nginx:debian-9
    environment:
       - MYSQL_ROOT_PASSWORD
       - MYSQL_DATABASE
       - MYSQL_USER
       - MYSQL_PASSWORD
    volumes:
      #montamos nuestra web desde el volumen externo
      - ./miweb/:/app
    ports:
      - 8000:80
    depends_on:
      - bd_mysql
    networks:
      - default

